Add theme support
slamdata/purescript-echarts pull request #30
Opened 2017-03-27 14:04 UTC by safareli

- update `Chart.init` to also take `Theme` as argument
- add `registerTheme` action
- update examples

2017-03-27 14:20 UTC, safareli commented on src/ECharts/Chart.js
> +            echarts.registerTheme(name, theme);
Does this check looks good?
```js
// if value is not `undefined` and is not of type `string` then it must be `Foreign` for which we only permit plain Objects.
if (theme !== undefined && typeof theme !== 'string' && !isObject(theme)) {
  throw new TypeError('Theme must be an Object')
}

function isObject(o) {
  return null != o && 
    typeof o === 'object' && 
    Object.prototype.toString.call(o) === '[object Object]';
}
```

2017-03-27 14:24 UTC, safareli commented on example/src/Themes.js
> +exports.themeDark = (function() {
btw we can add module `ECharts.Theme` like this
```js
// by just requiring they are registered
require("echarts/theme/roma");
require("echarts/theme/dark");
// require rest of themes here
```
```purescript
dark :: Theme
dark = ByName "dark"
-- define rest of `Theme`s
...
```

2017-03-27 14:31 UTC, cryogenian commented on example/src/Themes.js
> +exports.themeDark = (function() {
:+1: Are you going to add it in this pr?

2017-03-27 14:37 UTC, cryogenian requested changes

2017-03-27 14:37 UTC, cryogenian commented on src/ECharts/Chart.js
> +            echarts.registerTheme(name, theme);
Yeah, but please don't return `{}`

2017-03-27 14:37 UTC, cryogenian commented on example/src/Bar.purs
> +chart ∷ ∀ e. Maybe EC.Theme → Eff (random ∷ RANDOM, dom ∷ DOM, echarts ∷ ET.ECHARTS, err ∷ EXCEPTION|e) Unit
Could you please leave `chart` signature as is and make it something like `chart = chart' Nothing`?

2017-03-27 16:26 UTC, safareli commented on example/src/Scatter.purs
> +  chart' (ElementId "scatter-1") Nothing
do you wanted something like this?

2017-03-27 16:28 UTC, safareli commented on src/ECharts/Chart.js
> +            echarts.registerTheme(name, theme);
do you want to also remove `return {}` from other places too?

2017-03-27 16:29 UTC, safareli commented on src/ECharts/Theme.purs
> +foreign import forceExport :: Foreign
did this to make sure theme.js was included in output. is non hacky  way to do it?

2017-03-27 18:30 UTC, natefaubion commented on src/ECharts/Theme.purs
> +foreign import forceExport :: Foreign
One option would be to omit the foreign requires, and just tell library consumers to make sure the themes are included in their builds.

2017-03-27 18:59 UTC, cryogenian requested changes

2017-03-27 18:59 UTC, cryogenian commented on example/src/Scatter.purs
> +  chart' (ElementId "scatter-1") Nothing
Exactly :+1: This way it's backward compatible and we can make minor version update

2017-03-27 19:20 UTC, safareli commented on example/src/Scatter.purs
> +  chart' (ElementId "scatter-1") Nothing
why do we care about backward compatible updates in examples?

2017-03-27 19:27 UTC, cryogenian commented
Oh! Yep!
Let's define an ADT

data BuiltInTheme = Infographic | Macarons | Roma | Shine | Vintage | Dark 
Then define a func from it to string like

builtInThemeRoute :: BuiltInTheme -> String 
builtInThemeRoute = case _ of 
  Roma -> "echarts/theme/roma"
  _ -> ... 

builtinTheme :: BuiltInTheme -> Theme 
builtinTheme = case _ of 
  Roma -> "roma"
  _ -> ...
Then define a func that registers builtintheme

foreign import registerBuiltin_ ::  String-> Eff _ Unit
registerBuiltin :: BuiltInTheme -> Eff _ Theme
registerBuiltIn bit = builtinTheme bit <$ registerBuiltin_ (builtinThemeRoute bit)
and in Theme.js

exports.registerBuiltIn_ = function(route) {
  return function() {
    require(route);
  };
};
This way it's cleaner that registering builtin themes are effectful and they're actually predefined. And preserves notion of themes being open to extension by outside code.

2017-03-27 19:31 UTC, safareli commented
@cryogenian the option looks nice!

But it might have issues with dead code elimination. I think code analyzers will not be able to determine required pathes which are dynamic, if that issue is not a problem Will implement it as you pointed out.

2017-03-27 19:46 UTC, natefaubion commented
I would recommend not relying on dynamic requires.

2017-03-27 19:53 UTC, cryogenian commented
@natefaubion In this case it's actually isn't `require` but just an effect that registers an object as theme. (Basically stores an object to global map). 
So, yeah I know that this will bundle all themes to output, I'm not sure that this is a problem though.

2017-03-27 20:19 UTC, cryogenian commented on example/src/Scatter.purs
> +  chart' (ElementId "scatter-1") Nothing
That's not about examples, but about API. If we preserve `chart` signature, then API isn't changed and it's a minor version bump. 
I've just put comment here, not there :D

2017-03-27 21:01 UTC, natefaubion commented
The bundler can't pick up opaque dynamic requires though.

2017-03-28 09:53 UTC, safareli commented on example/src/Scatter.purs
> +      ch ← maybe EC.init EC.initWithTheme theme el
looks good?

2017-03-28 10:09 UTC, safareli commented
I think it would be better to just state in readme to include themes client is want's to use in there bundler, as otherwise we have two options:

- Do what I have done currently. But, even if user is using just `Theme` type (no build in themes are sued), then `Theme` module will be bundled in output and I think, it will contain unused build in themes, which we don't want.

- Do as Maxim suggested, But bundlers will not be able to determine what should be included in output and clients might need to explicitly add theme pathes to there bundler configuration. 

Do you agree, or am I missing something?

2017-03-28 12:07 UTC, cryogenian approved these changes

2017-03-28 12:08 UTC, cryogenian commented
Ok, I think this is good to go. BTW, we can also use one module per theme. This way if user import theme it's `require`d. But I think this is a matter of different pr.

2017-03-28 12:08 UTC, merged